### ISSUE TITLE
Calendar colors illegible

### ISSUE THREAD

**Issue by joonro** [hulihanapplications/axiom#3]
Hi,

Thanks for the great theme. I really like it, except in the calendar tab, colors are illegible.
For example, "issue beginning this day" box has silver front and dark yellow bg. Also, the floating box when I hover cursor to the "issue beginning this day" box has silver front/bg for some parts.

-Joon

**Comment by dhulihan** [comment]
Hi Joon - 
Thanks for the feedback and for noticing the ugly calendar stuff. I've updated the stylesheet in [543bec](https://github.com/hulihanapplications/axiom/commit/543bec986c491a68c8065f69faf40cc92905969a), so it should look much better now. Let me know if you see anything else!

**Comment by joonro** [comment]
Thanks for the quick fix. It looks great! I will let you know if I see anything else. Thanks again for the great theme.
