### ISSUE TITLE
SSL Error with Google Font

### ISSUE THREAD

**Issue by wwb** [hulihanapplications/axiom#5]
If you are running your issue tracker behind SSL like you should be, it turns out this theme causes errors in some browsers. The issue is the call to the google font is absolute where it should be protocol-relative.

I posted the fix over at https://gist.github.com/3813017 since I don't have git handy to submit a pull request. Should be able to patch that right in . . .

**Comment by dhulihan** [comment]
Thanks for the patch. I've merged it as 5033240. Easy-peasy!
