### ISSUE TITLE
repository diff color

### ISSUE THREAD

**Issue by joonro** [hulihanapplications/axiom#6]
Hi,

I just found that repository diff colors are all white on black background with axiom theme.
Thanks!

**Comment by dhulihan** [comment]
It should look a little better in eeafd90be1936a18824ca8c2a91fb15c7b6e8a59. Let me know if I missed anything.

![Diff Repo Test Redmine](https://f.cloud.github.com/assets/519728/61079/a9957222-5c32-11e2-8702-8a4209d5aa1e.png)
